poll/urls.py
from django.conf.urls.defaults import *
from . import views

urlpatterns = patterns(
    '',
    url(r'^dashboard/$', views.dashboard),
    url(r'^latest_messages$',views.latest_messages),
    url(r"^$", views.polls, name="polls"),
    url(r"^(\d+)/submissions.csv$", views.responses_as_csv),
    url(r"^new/$", views.new_poll),
    url(r"^(\d+)/responses/$", views.view_responses, name="poll-responses"),
    url(r"^(?P<poll_id>\d+)/responses/module/$", views.view_responses,  {'as_module':True}, name="poll-responses-module"),
    url(r"^responses/(\d+)/view/$", views.view_response),
    url(r"^(\d+)/report/$", views.view_report, name="poll-report"),
    url(r"^(\d+)/report/(\d+)/$", views.view_report, name="poll-report"),
    url(r"^(?P<poll_id>\d+)/report/module/$", views.view_report, {'as_module':True}, name="poll-report-module"),
    url(r"^(\d+)/report/(\d+)/module/$", views.view_report, {'as_module':True}, name="poll-report-location-module"),

    url(r"^responses/(\d+)/edit/$", views.edit_response),
    url(r"^responses/(\d+)/apply/$", views.apply_response),
    url(r"^responses/(\d+)/apply_all/$", views.apply_all),
    url(r"^responses/(\d+)/delete/$", views.delete_response),
    url(r"^responses/(?P<poll_id>\d+)/stats/$", views.stats, name="poll-stats"),
    url(r"^responses/(?P<poll_id>\d+)/stats/(?P<location_id>\d+)/$", views.stats, name="poll-stats"),
    url(r"^responses/(?P<poll_id>\d+)/numeric/$", views.number_details),
    url(r"^(\d+)/view/$", views.view_poll),
    url(r"^(\d+)/details/$", views.view_poll_details),
    url(r"^(\d+)/edit/$", views.edit_poll),
    url(r"^(\d+)/delete/$", views.delete_poll),
    url(r"^(\d+)/start/$", views.start_poll),
    url(r"^(\d+)/end/$", views.end_poll),
    url(r"^(\d+)/add_category/$", views.add_category),
    url(r"^(\d+)/edit_category/(\d+)/$", views.edit_category),
    url(r"^(\d+)/category/(\d+)/$", views.view_category),
    url(r"^(\d+)/delete_category/(\d+)/$", views.delete_category),
    url(r"^(\d+)/category/(\d+)/rule/(\d+)/$", views.view_rule),
    url(r"^(\d+)/category/(\d+)/rule/(\d+)/edit/$", views.edit_rule),
    url(r"^(\d+)/category/(\d+)/rules/add/$", views.add_rule),
    url(r"^(\d+)/category/(\d+)/rule/(\d+)/delete/$", views.delete_rule),
    url(r"^(\d+)/category/(\d+)/rules/$", views.view_rules),
    url(r"^(\d+)/categories/add/$", views.add_category),
    url(r"^(\d+)/demo/", views.demo, name="demo"),

    url(r"^/activity_as_csv/$", views.activity_as_csv),
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from poll import views

admin.autodiscover()


urlpatterns = patterns('',

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    (r'^admin/', include(admin.site.urls)),

    # RapidSMS core URLs
    (r'^account/', include('rapidsms.urls.login_logout')),

    url(r'^$', views.dashboard, name='rapidsms-dashboard'),
    url(r'^activity_as_csv/$', views.activity_as_csv),

    # RapidSMS contrib app URLs
    (r'^ajax/', include('rapidsms.contrib.ajax.urls')),
    (r'^export/', include('rapidsms.contrib.export.urls')),
    (r'^httptester/', include('rapidsms.contrib.httptester.urls')),
    (r'^locations/', include('rapidsms.contrib.locations.urls')),
    (r'^messagelog/', include('rapidsms.contrib.messagelog.urls')),
    (r'^messaging/', include('rapidsms.contrib.messaging.urls')),
    (r'^scheduler/', include('rapidsms.contrib.scheduler.urls')),

    # Haruka specific
    (r'^registration/', include('registration.urls')),
    (r'^groups/', include('groups.urls')),
    (r'^bulksend/', include('bulksend.urls')),
    ('', include('rapidsms_xforms.urls')),
    ('^polls/', include('poll.urls')),
    ('', include('rapidsms_httprouter.urls')),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

urlpatterns += patterns('',
    # helper URLs file that automatically serves the 'static' folder in
    # INSTALLED_APPS via the Django static media server (NOT for use in
    # production)
    (r'^', include('rapidsms.urls.static_media')),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT,}),
 
)
urlpatterns += staticfiles_urlpatterns()

poll/forms.py
from django import forms

#from django.contrib.auth.models import Group
from .models import Poll, Category, Rule ,Translation
from rapidsms.models import Contact
from groups.models import Group
from django.forms.widgets import RadioSelect

import re


class ReplyForm(forms.Form):
    recipient = forms.CharField(max_length=20)
    message = forms.CharField(max_length=160, widget=forms.TextInput(attrs={'size':'60'}))


class NewPollForm(forms.Form): # pragma: no cover

    TYPE_YES_NO = 'yn'
    choices = [(choice['type'], choice['label']) for choice in Poll.TYPE_CHOICES.values()]
    choices.append((TYPE_YES_NO, 'Yes/No Question'))

    poll_type = forms.ChoiceField(
               required=True,
               choices=tuple(choices)
               )
    response_type=forms.ChoiceField(choices=Poll.RESPONSE_TYPE_CHOICES,widget=RadioSelect,initial=Poll.RESPONSE_TYPE_ALL)

    def updateTypes(self):
        self.fields['poll_type'].widget.choices = [(NewPollForm.TYPE_YES_NO, 'Yes/No Question')]
        self.fields['poll_type'].widget.choices += [(choice['type'], choice['label']) for choice in Poll.TYPE_CHOICES.values()]

    name = forms.CharField(max_length=32, required=True)
    question = forms.CharField(max_length=160, required=True, widget=forms.Textarea())
    question_luo = forms.CharField(max_length=160, required=False, widget=forms.Textarea())
    default_response = forms.CharField(max_length=160, required=False, widget=forms.Textarea())
    default_response_luo = forms.CharField(max_length=160, required=False, widget=forms.Textarea())
    start_immediately = forms.BooleanField(required=False)
    contacts = forms.ModelMultipleChoiceField(queryset=Contact.objects.all(), required=False)
    groups = forms.ModelMultipleChoiceField(queryset=Group.objects.all(), required=False)

    # This may seem like a hack, but this allows time for the Contact model
    # to optionally have groups (i.e., poll doesn't explicitly depend on the rapidsms-auth
    # app.
    #def __init__(self, data=None, **kwargs):
    #    if data:
    #        forms.Form.__init__(self, data, **kwargs)
    #    else:
    #        forms.Form.__init__(self, **kwargs)
    #    if hasattr(Contact, 'groups'):
    #        self.fields['groups'] = forms.ModelMultipleChoiceField(queryset=Group.objects.all(), required=False)

    def clean(self):
        cleaned_data = self.cleaned_data
        contacts = cleaned_data.get('contacts')
        groups = cleaned_data.get('groups')
        if cleaned_data.has_key('question'):
            cleaned_data['question'] = cleaned_data.get('question').replace('%', u'\u0025')
        if 'default_response' in cleaned_data:
            cleaned_data['default_response'] = cleaned_data['default_response'].replace('%', u'\u0025')

        if not contacts and not groups:
            raise forms.ValidationError("You must provide a set of recipients (either a group or a contact)")

        return cleaned_data

class PollTranslation(forms.ModelForm):
    class Meta:
        model = Translation
class EditPollForm(forms.ModelForm): # pragma: no cover
    class Meta:
        model = Poll
        fields = ('name', 'default_response')

    def clean(self):
        cleaned_data = self.cleaned_data
        cleaned_data['default_response'] = cleaned_data.get('default_response').replace('%', u'\u0025')
        return cleaned_data

    # This may seem like a hack, but this allows time for the Contact model's
    # default manage to be replaced at run-time.  There are many applications
    # for that, such as filtering contacts by site_id (as is done in the
    # authsites app, see github.com/daveycrockett/authsites).
    # This does, however, also make the polling app independent of authsites.
    def __init__(self, data=None, **kwargs):
        if data:
            forms.ModelForm.__init__(self, data, **kwargs)
        else:
            forms.ModelForm.__init__(self, **kwargs)
        if 'instance' in kwargs:
            self.fields['contacts'] = forms.ModelMultipleChoiceField(queryset=Contact.objects.all(), initial=kwargs['instance'].contacts.all())
        else:
            self.fields['contacts'] = forms.ModelMultipleChoiceField(queryset=Contact.objects.all())

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=50, required=True)
    default = forms.BooleanField(required=False)
    response = forms.CharField(max_length=160, required=False)
    priority = forms.IntegerField(required=False, widget=forms.Select(
            choices=tuple([('', '---')] + [(i, "%d" % i) for i in range(1, 11)])))
    color = forms.CharField(required=False, max_length=6, widget=forms.Select(choices=(
                (None, '---'),
                ('ff9977', 'red'),
                ('99ff77', 'green'),
                ('7799ff', 'blue'),
                ('ffff77', 'yellow'))))

    def clean(self):
        cleaned_data = self.cleaned_data
        cleaned_data['response'] = cleaned_data.get('response').replace('%', u'\u0025')
        return cleaned_data

    class Meta:
        model = Category
        fields = ('name', 'priority', 'color', 'default', 'response')

class RuleForm(forms.ModelForm):
    rule_string = forms.CharField(max_length=256, required=True)
    rule_type = forms.CharField(max_length=2, required=False, widget=forms.Select(choices=Rule.RULE_CHOICES))
    class Meta:
        model = Rule
        fields = ('rule_type', 'rule_string')

    def clean(self):
        cleaned_data = self.cleaned_data
        rule_string = cleaned_data.get('rule_string')
        rule_type = cleaned_data.get('rule_type')
        if rule_type == 'r':
            try:
                re.compile(rule_string)
            except:
                self._errors['rule_string'] = self.error_class([u"You must provide a valid regular expression"])
                del cleaned_data['rule_string']

        # Always return the full collection of cleaned data.
        return cleaned_data

haruka_theme/templates/polls/category_edit.html
{% load i18n %}
<td class="category_name_col">
    {% if not category %}
        <div class="add_category_header">{% trans "Add New Category" %}</div>
    {% endif %}
    <script language="javascript">
      $(document).ready(function() {
        // highlight the save button when changes are detected
        $("input,select").change(function() { 
            category_id = '{{ category.pk }}'
            $("#save_" + category_id).addClass("positive");
        });
      });
      
    </script>

  {% if category %}
  
  {% endif %} {{ form.name }} {{ form.name.errors}}</td>
<td class="category_response_col">{{ form.response }} {{form.command.errors}}</td>
<!--<td class="category_priority_col">{{ form.priority }} {{ form.priority.errors }}</td>-->
<td class="category_color_col" {% if form.color %}style="background-color:#{{ form.color.value }}"{% endif %}>{{ form.color }} {{ form.color.errors }}</td>
<td class="category_default_col">{{ form.default }} {{ form.default.errors }}</td>
<td class="category_options_col">
  
  {% if category %}
      <a style="float:right;padding-top:7px;" href="javascript:void(0);"><img onclick="cancelCategory(this, '{% url poll.views.view_category poll.pk category.pk %}');" src="{{ STATIC_URL }}icons/silk/decline.png" alt="" border="0"/></a>  
      <div>
          <a class='btn success' onclick="saveCategory(this, '{% url poll.views.edit_category poll.pk category.pk %}');" href="javascript:void(0);" id="save_{{ category.pk }}">{% trans "Save" %}
          </a>
      </div>
  {% else %}  
      <a href="javascript:void(0);"><img onclick="cancelAdd(this);" style="float:right;padding-top:6px;" src="{{ STATIC_URL }}icons/silk/decline.png" alt="" border="0"/></a>  
      <div class="buttons">
          <a onclick="addCategory(this);" href="javascript:void(0);" id="save_{{ category.pk }}" class="positive">
              <img src="{{ STATIC_URL }}icons/silk/add.png" alt=""/>{% trans "Add" %}
          </a>
      </div>
  {% endif %}
  </td>
</form>

haruka_theme/templates/polls/category_view.html
{% load i18n %}
<td class="category_name_col">
  {{ category.name }}
</td>
<td class="category_response_col">{{ category.response }}</td>
<!--<td class="category_priority_col">{{ category.priority }}</td>-->
<td class="category_color_col" {% if category.color %}style="background-color:#{{ category.color }}"{% endif %}>
  &nbsp;
</td>
<td class="category_default_col">
  {% if category.default %}
    <img style="vertical-alignment:bottom;padding-top:7px" src="{{ STATIC_URL }}icons/silk/accept.png" alt="This category is default"/>
  {% else %}
    &nbsp;
  {% endif %}
</td>
<td class="category_options_col">
  <a onclick="deleteCategory(this, '{% url poll.views.delete_category poll.pk category.pk %}');" class="negative" style="float:right">
    <img style="vertical-alignment:bottom;padding-top:7px" src="{{ STATIC_URL }}icons/silk/delete.png" alt=""/>
  </a>
  <div>
    <a class="btn" onclick="editCategory(this, '{% url poll.views.edit_category poll.pk category.pk %}');" href="javascript:void(0);">{% trans "Edit" %}</a>
    {% ifequal poll.type 't' %}
<!--    <a href="{% url poll.views.view_rules  poll.pk category.pk %}" id="save_{{ category.pk }}">
      <img src="{{ MEDIA_URL }}poll/icons/silk/bullet_wrench.png" alt=""/>Rules ({{ category.rules.all.count }})
    </a>-->
    {% endifequal %}
  </div>
</td>

haruka_theme/templates/polls/layout.html
{% extends "layout.html" %}
{% load i18n %}
{% block title %}{% trans "HarukaSMS - Polls" %}{% endblock %}

{% block stylesheets %}
{{ block.super }}
<link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}stylesheets/style.css" />
<link rel="stylesheet" href="{{ STATIC_URL }}stylesheets/uni-form-generic.css" type="text/css" />
<link rel="stylesheet" href="{{ STATIC_URL }}stylesheets/uni-form.css" type="text/css" />
<link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}haruka_theme/css/bootstrap.css" />
<link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}haruka_theme/css/custom.css" />
{% endblock %}


{% block javascripts %}
<script src="{{ STATIC_URL }}javascripts/uni-form.jquery.js" type="text/javascript"></script>
{% endblock %}

{% block breadcrumbs %}


{% endblock %}

haruka_theme/templates/polls/poll_create.html
{% extends "polls/layout.html" %}
{% load i18n %}
{% block title %}{% trans "HarukaSMS - Polls" %}{% endblock %}

{% block content %}

{% load uni_form_tags %}
{% load forms_tags %}

	<h4 style='margin-left:150px; margin-top: 45px;'>{% trans "Create a New Poll" %} <blockquote><small>{% trans "create a simple SMS poll that includes either a yes no response or a numbered response -- but with no keywords needed!" %}</small></blockquote></h4>

<div id='newForm1'>
	<form action="{% url poll.views.new_poll %}" method="post" class="uniForm" id='newForm'>
		<fieldset>
			{{ form|as_uni_form }}
			<div class='poll-buttons'>
				<a class='btn' href="{% url polls %}">
				<!-- <img src="{{ STATIC_URL }}icons/silk/decline.png" alt=""/> -->
				{% trans "Cancel" %}
				</a>
				<a class='btn primary' onclick="$('#newForm').submit();" href="javascript:void(0);">
				<!--<img src="{{ STATIC_URL }}icons/silk/add.png" alt=""/> -->
				{% trans "Create Poll" %}
				</a>
			</div>
		</fieldset>
		{% csrf_token %}
	</form>
</div>


{% endblock %}

haruka_theme/templates/polls/poll_dashboard.html
{% extends "polls/layout.html" %}
{% load i18n %}

{% block title %}{% trans "HarukaSMS - Activity" %}{% endblock %}
{% block javascripts %}
    {{ block.super }}
    <script src="{{ STATIC_URL }}javascripts/polls.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}haruka_theme/js/bootstrap-scrollspy.js" type="text/javascript"></script>
{% endblock %}
{% block content %}

<div class="row">
	<div class="span6">
		<h4 id="quick-SMS-h4">{% trans "Quick SMS" %}</h4>
			<div class="well quick_SMS">
				<form method="POST" class="sender-form">
					{% if reply_form.recipient.errors %}
						{{ reply_form.recipient.errors }}
					{% endif %}
					<label for="id_{{ reply_form.recipient.name }}">{{ reply_form.recipient.label }}:</label>{{ reply_form.recipient }}
					<br/>
					{% if reply_form.message.errors %}
						{{ reply_form.message.errors }}
					{% endif %}
					<label for="id_{{ reply_form.message.name }}">{{ reply_form.message.label }}:</label>{{ reply_form.message }}
					<input type="hidden" name="action" value="reply" />
					<input type="submit" value="send" class='btn primary' id="quick-SMS-btn"/>
					{% csrf_token %}
				</form>
				<script language="javascript">
					function reply(number) {
					$('#id_recipient').val(number);
					return void(0);
					}
				</script>
			</div>
		<div class="data-box">
			<h4>{% trans "Your Latest Polls" %}</h4>
		  	<table class="condensed-table">
		  		<thead>
		      		<tr>
		        		<th class="poll_name_col">{% trans "Poll Name" %}</th>
		        	<th class="poll_question_col display-none">{% trans "Question" %}</th>
		        		<th class="poll_date_col display-none">{% trans "Start Date" %}</th>
		        		<th class="poll_date_col display-none">{% trans "Activity" %}</th>
		        		<th class="poll_submissions">{% trans "Submissions" %}</th>
		      		</tr>
		    	</thead>
		    	<tbody>
		      		{% if polls %}
		      		{% for poll in polls %}
		      		<tr class="condensed-table">
		        		<td><a href="/polls/{{ poll.pk }}/responses/">{{ poll.name }}</a></td>
		        	<td class="display-none"><b>{% if poll.start_date %}{{ poll.question }}{% else %}<font color="grey">{{ poll.question }}</font>{% endif %}</b></td>
		        	<td class="display-none">{% if poll.start_date %}{{ poll.start_date|date:"d/m/Y" }}{% endif %}</td>
		        	<td class="display-none">{% if poll.end_date %}{{ poll.end_date|date:"d/m/Y" }}{% else %}Still Open{% endif %}</td>
		        		<td class="cell-phone"><span class="phone-count">{{ poll.responses.distinct.count }}
		            		{% if poll.contacts.count > 1 %}
		              		of {{ poll.contacts.count }} ({% widthratio poll.responses.distinct.count poll.contacts.count 100 %}%)
		            		{% endif %}</span>
		           		</td>
		      		</tr>
		      		{% endfor %}
		      		{% else %}
		     		 <tr class="poll_table_row">
		        		<td colspan="5"><i>{% trans "No existing Polls.  Click on 'Polls' to create one." %}</i></td>
		     		 </tr>
		      		{% endif %}
		    	</tbody>
		    </table>
		
		  	<h4>{% trans "Your Latest Data Collection" %}</h4>
		  	<table class="condensed-table">
		    	<thead>
		      		<tr>
		        		<th class="poll_name_col">{% trans "Activity Name" %}</th>
		        	<th class="poll_question_col display-none">{% trans "Keyword" %}</th>
		        		<th class="poll_date_col display-none">{% trans "Description" %}</th>
		        		<th class="poll_date_col display-none">{% trans "Start Date" %}</th>
		       			<th class="poll_date_col display-none">{% trans "Activity" %}</th>
		        		<th class="poll_submissions">{% trans "Submissions" %}</th>
		      		</tr>
		    	</thead>
		    	<tbody>
		      		{% if data_collections %}
		      		{% for data_collection in data_collections %}
		      		<tr class="condensed-table">
		        		<td><a href="/xforms/{{ data_collection.pk }}/submissions/">{{ data_collection.name }}</a></td>
		        		<td class="display-none"><b>{{ data_collection.keyword }}</b></td>
		        		<td class="display-none">{{ data_collection.description }}</td>
		        		<td class="display-none">{% if data_collection.created %}{{ data_collection.created|date:"d/m/Y" }}{% endif %}</td>
		        		<td class="display-none">{% if data_collection.active %} Still Open {% else %} Closed {% endif %}</td>
		
		        		<td class="cell-phone"><span class="phone-count">{{ data_collection.submissions.distinct.count }}</span>
		           		</td>
		      		</tr>
		      {% endfor %}
		      {% else %}
		      		<tr class="poll_table_row">
		        		<td colspan="5"><i>{% trans "No existing Data Collection activities.  Click on 'Data Collection' to create one." %}</i></td>
		      		</tr>
		      {% endif %}
		    	</tbody>
			</table>
		
		</div> <!-- Data Box Div -->
	</div><!-- Span 6 Div -->

	<div class="span8" id="activity-margins">

		  <h4>{% trans "Latest Activity" %}</h4>
		  	<a href="/activity_as_csv/"><img id="download-activity" src='{{STATIC_URL}}images/download-alt.png'/></a>
<!--		  	<body data-spy="scroll" >-->
		  	
		  		<div id="condensed-table">
		      		{{ messages_table|safe }}
		  		</div>
		  		<!--<a class="more_msg" href="/router/console">More Messages</a>-->
		  		<script type="text/javascript">
				    function update() {
				        $.get("/polls/latest_messages", function(data) {
				        $("#messages_table").html(data);
				            window.setTimeout(update, 5000);
				        });
				    }
				    window.setTimeout(update, 5000);
		  		</script>
		  		<script type="text/javascript">
					$(function() {
						$('#navbar').scrollspy();
					});	
				</script>
<!--		  	</body>	-->
	</div>	
</div>
{% endblock %}

haruka_theme/templates/polls/poll_details.html
{% load i18n %}
<style>

.add_category_header {
    background-color: none;
    color: transparent;
    padding-bottom: 0px;
    padding-left: 0px;
    padding-top: 0px;
    height:0px;
}

</style>
<div>
    {% if not poll.start_date %}
    <a onclick="editPollDetails();" href="javascript:void(0);" class='btn'> 
       {% trans "Edit" %}
    </a>
    <form style="border:0px" action="{% url poll.views.start_poll poll.pk %}" method="POST" id="startPollForm">
    <a onclick="submitForm(this, '#poll_header');" href="javascript:void(0);" class='btn success'> 
        {% trans "Start Poll" %}
    </a>
    </form>
    {% endif %}
    {% if poll.start_date and not poll.end_date %}
    <form style="border:0px" action="{% url poll.views.end_poll poll.pk %}" method="POST" id="closePollForm">
    <a onclick="submitForm(this, '#poll_header');" href="javascript:void(0);" class='btn'>
        {% trans "Close Poll" %}
    </a>
    </form>    
    {% endif %}
</div>
<div class="name">{{ poll.name }} 
  <span class="participants">({{ poll.contacts__count }} participant{{ poll.contacts__count|pluralize }})</span>
</div>
<div class="question">{{ poll.question }}</div>
<div class="response">{% trans "Response:" %} {{ poll.default_response }}</div>

haruka_theme/templates/polls/poll_edit.html
{% load i18n %}

<div class="name">{% trans "Edit" %} '{{poll.name}}'</div>

{% load uni_form_tags %}

<form action="{% url poll.views.edit_poll poll.pk %}" method="post" class="uniForm">
<fieldset>
{{form|as_uni_form}}


  <a class='btn'="showPollDetails('{{ poll.pk }}');" href="javascript:void(0);" class="negative" class='btn'>
    {% trans "Cancel" %}
  </a>
  <a onclick="submitForm(this, '#poll_header');" href="javascript:void(0);" class='btn primary'>
    {% trans "Save Poll Details" %}
  </a>

</fieldset>
</form>

haruka_theme/templates/polls/poll_index.html
{% extends "polls/layout.html" %}
{% load i18n %}
{% block title %}{% trans "HarukaSMS - Polls" %}{% endblock %}
{% block javascripts %}
    {{ block.super }}
    <script src="{{ STATIC_URL }}javascripts/polls.js" type="text/javascript"></script>

{% endblock %}
{% block content %}

<a class="btn large primary" style="margin-bottom:30px; margin-top: 45px; margin-left: 20px; " href="{% url poll.views.new_poll %}"> {% trans "Add New Poll" %} </a> 

<table class="condensed-table" style="width:878px; margin-left:20px;"> 
  <thead> 
    <tr>
      <th class="poll_name_col">{% trans "Name" %}</th>  
      <th class="poll_question_col" style='width:290px;'>{% trans "Question" %}</th>
      <th class="poll_date_col">{% trans "Start Date" %}</th>
      <th class="poll_date_col">{% trans "Closing Date" %}</th>
      <th class="poll_options_col" style='width:212px;'></th> 
    </tr> 
  </thead> 
  <tbody>
    {% if polls %}
    {% for poll_obj in polls %}
    <tr class="table">
      <td>{{ poll_obj.name }}</td>
      <td><b>{% if poll_obj.start_date %}{{ poll_obj.question }}{% else %}<font color="grey">{{ poll_obj.question }}</font>{% endif %}</b></td>
      <td>{% if poll_obj.start_date %}{{ poll_obj.start_date|date:"d/m/Y" }}{% endif %}</td>
      <td>{% if poll_obj.end_date %}{{ poll_obj.end_date|date:"d/m/Y" }}{% else %}Open{% endif %}</td>      
      <td>
          <a style="float:right;padding-top:7px;" href="javascript:void(0);" onclick="deletePoll(this, '{% url poll.views.delete_poll poll_obj.pk %}','{{poll_obj.question|addslashes}}');"><img border="0" src="{{ STATIC_URL }}icons/silk/delete.png"/></a>
          <div>
              {% if poll_obj.responses__count %}
<!--                  <a href="{% url poll-report poll_obj.pk %}">  </a>-->
<!--                        <img src="{{ STATIC_URL }}icons/silk/zoom.png" alt=""/> Report-->
                  </a>
            	  <a href="{% url poll-responses poll_obj.pk %}" class="btn">
                        {% trans "Responses" %}({{ poll_obj.responses__count }})</a>
	          {% endif %}
	          <a href="{% url poll.views.view_poll poll_obj.pk %}" class="btn">{% trans "Edit" %}</a>
	      </div>
      </td>
    </tr>
    {% endfor %}
    {% else %}
    <tr class="poll_table_row">
      <td colspan="5"><i>{% trans "No existing Polls.  Click 'Add New Poll' to create one." %}</i></td>
    </tr>
    {% endif %}
  </tbody>
</table>
<br/>



<br/><br/>

<br/>



<form name="form" method="post" action="">
{% csrf_token %}
</form>


{% endblock %}

haruka_theme/templates/polls/poll_report.html
{% extends "polls/layout.html" %}
{% load i18n %}
{% block title %}{% trans "HarukaSMS - Polls" %}{% endblock %}

{% block javascripts %}
{{ block.super }}
<script type="text/javascript" src="{{ MEDIA_URL }}poll/javascripts/poll.js"></script> 
{% endblock %}

{% block content %}
    <div id="poll_report">
        {% ifequal poll.type 't' %}
            {% include "polls/poll_report_text.html" %}
        {% else %}
            {% ifequal poll.type 'n' %}
                {% include "polls/poll_report_numeric.html" %}
            {% endifequal %}
        {% endifequal %}
    </div>
{% endblock %}